"""
Data models and DTO schemas for the Social Media Crawler Engine.
Matches 1:1 with frontend/backend TypeScript definitions in media.dto.ts.
"""

from dataclasses import dataclass, field, asdict
from typing import List, Optional, Union, Dict, Any


@dataclass
class StreamFormat:
    format_id: str
    quality: Optional[str] = None
    format: Optional[str] = None
    size: Optional[str] = None
    stream_type: str = "full"  # 'full' | 'mute' | 'audio' | 'stream' | 'muxed'
    raw_size: Optional[int] = None
    has_audio: Optional[bool] = None
    has_video: Optional[bool] = None
    fps: Optional[str] = None
    bitrate: Optional[str] = None
    url: Optional[str] = None
    vcodec: Optional[str] = None
    acodec: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        res = {
            "formatId": self.format_id,
            "quality": self.quality,
            "format": self.format,
            "size": self.size,
            "streamType": self.stream_type,
        }
        if self.raw_size is not None:
            res["rawSize"] = self.raw_size
        if self.has_audio is not None:
            res["hasAudio"] = self.has_audio
        if self.has_video is not None:
            res["hasVideo"] = self.has_video
        if self.fps:
            res["fps"] = self.fps
        if self.bitrate:
            res["bitrate"] = self.bitrate
        if self.url:
            res["url"] = self.url
        if self.vcodec:
            res["vcodec"] = self.vcodec
        if self.acodec:
            res["acodec"] = self.acodec
        return res


@dataclass
class SubtitleItem:
    lang: str
    name: str
    ext: str
    url: Optional[str] = None
    is_auto_generated: Optional[bool] = None

    def to_dict(self) -> Dict[str, Any]:
        res = {"lang": self.lang, "name": self.name, "ext": self.ext}
        if self.url:
            res["url"] = self.url
        if self.is_auto_generated is not None:
            res["isAutoGenerated"] = self.is_auto_generated
        return res


@dataclass
class ChapterItem:
    title: str
    start_time: float
    end_time: float
    start_formatted: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "title": self.title,
            "startTime": self.start_time,
            "endTime": self.end_time,
            "startFormatted": self.start_formatted,
        }


@dataclass
class MediaImage:
    id: Union[str, int]
    url: str
    title: Optional[str] = None
    resolution: Optional[str] = None
    size: Optional[str] = None
    type: Optional[str] = "image"  # 'image' | 'video' | 'gif'
    ext: Optional[str] = None
    thumb: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        res = {
            "id": self.id,
            "url": self.url,
            "title": self.title,
            "type": self.type or "image",
        }
        if self.resolution:
            res["resolution"] = self.resolution
        if self.size:
            res["size"] = self.size
        if self.ext:
            res["ext"] = self.ext
        if self.thumb:
            res["thumb"] = self.thumb
        return res


@dataclass
class CrawlMediaItem:
    id: Union[str, int]
    type: str  # 'video' | 'image' | 'audio'
    title: Optional[str] = None
    thumb: Optional[str] = None
    url: Optional[str] = None
    duration: Optional[str] = None
    quality: Optional[str] = None
    size: Optional[str] = None
    author: Optional[str] = None
    upload_date: Optional[str] = None
    views: Optional[str] = None
    likes: Optional[str] = None
    is_live: Optional[bool] = None
    is_reel: Optional[bool] = None
    is_short: Optional[bool] = None
    # Một bài đăng có thể chứa nhiều tệp (carousel Instagram, album Facebook,
    # post nhiều ảnh trên X/Bluesky). Bốn trường dưới đây giữ lại quan hệ
    # "tệp này thuộc bài đăng nào, là tệp thứ mấy / trên tổng bao nhiêu" để giao
    # diện gom nhóm được và tên tệp tải về không đụng nhau.
    post_id: Optional[str] = None
    post_url: Optional[str] = None
    index_in_post: Optional[int] = None
    total_in_post: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        res = {
            "id": self.id,
            "type": self.type,
            "title": self.title,
            "thumb": self.thumb,
            "url": self.url,
        }
        if self.post_id:
            res["postId"] = self.post_id
        if self.post_url:
            res["postUrl"] = self.post_url
        if self.index_in_post is not None:
            res["indexInPost"] = self.index_in_post
        if self.total_in_post is not None:
            res["totalInPost"] = self.total_in_post
        if self.duration:
            res["duration"] = self.duration
        if self.quality:
            res["quality"] = self.quality
        if self.size:
            res["size"] = self.size
        if self.author:
            res["author"] = self.author
        if self.upload_date:
            res["uploadDate"] = self.upload_date
        if self.views:
            res["views"] = self.views
        if self.likes:
            res["likes"] = self.likes
        if self.is_live is not None:
            res["isLive"] = self.is_live
        if self.is_reel is not None:
            res["isReel"] = self.is_reel
        if self.is_short is not None:
            res["isShort"] = self.is_short
        return res


@dataclass
class MediaMetadata:
    id: str
    platform: str
    title: Optional[str] = None
    author: Optional[str] = None
    author_url: Optional[str] = None
    duration: Optional[str] = None
    views: Optional[str] = None
    thumbnail: Optional[str] = None
    type: str = "video"  # 'video' | 'album' | 'audio' | 'playlist' | 'live'
    original_url: str = ""
    likes: Optional[str] = None
    comments: Optional[str] = None
    high_res_thumbnail: Optional[str] = None
    description: Optional[str] = None
    tags: Optional[List[str]] = None
    upload_date: Optional[str] = None
    subtitles: Optional[List[SubtitleItem]] = None
    chapters: Optional[List[ChapterItem]] = None
    streams: Optional[List[StreamFormat]] = None
    images: Optional[List[MediaImage]] = None
    playlist_items: Optional[List[CrawlMediaItem]] = None
    is_live: Optional[bool] = None
    live_stream_url: Optional[str] = None
    is_reel: Optional[bool] = None
    is_short: Optional[bool] = None
    playlist_count: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        res = {
            "id": self.id,
            "platform": self.platform,
            "title": self.title,
            "author": self.author,
            "authorUrl": self.author_url,
            "duration": self.duration,
            "views": self.views,
            "thumbnail": self.thumbnail,
            "type": self.type,
            "originalUrl": self.original_url,
        }
        if self.likes:
            res["likes"] = self.likes
        if self.comments:
            res["comments"] = self.comments
        if self.high_res_thumbnail:
            res["highResThumbnail"] = self.high_res_thumbnail
        if self.description:
            res["description"] = self.description
        if self.tags is not None:
            res["tags"] = self.tags
        if self.upload_date:
            res["uploadDate"] = self.upload_date
        if self.subtitles is not None:
            res["subtitles"] = [s.to_dict() for s in self.subtitles]
        if self.chapters is not None:
            res["chapters"] = [c.to_dict() for c in self.chapters]
        if self.streams is not None:
            res["streams"] = [s.to_dict() for s in self.streams]
        if self.images is not None:
            res["images"] = [img.to_dict() for img in self.images]
        if self.playlist_items is not None:
            res["playlistItems"] = [it.to_dict() for it in self.playlist_items]
        if self.is_live is not None:
            res["isLive"] = self.is_live
        if self.live_stream_url:
            res["liveStreamUrl"] = self.live_stream_url
        if self.is_reel is not None:
            res["isReel"] = self.is_reel
        if self.is_short is not None:
            res["isShort"] = self.is_short
        if self.playlist_count is not None:
            res["playlistCount"] = self.playlist_count
        return res


@dataclass
class ProfileCrawlResult:
    platform: str
    name: Optional[str] = None
    handle: Optional[str] = None
    url: str = ""
    avatar: Optional[str] = None
    stats: Optional[str] = None
    media: List[CrawlMediaItem] = field(default_factory=list)
    total_count: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        res = {
            "platform": self.platform,
            "name": self.name,
            "handle": self.handle,
            "url": self.url,
            "avatar": self.avatar,
            "stats": self.stats,
            "media": [m.to_dict() for m in self.media],
        }
        if self.total_count is not None:
            res["totalCount"] = self.total_count
        return res


@dataclass
class ResolveUrlResult:
    original_url: str
    resolved_url: str
    platform: str
    platform_name: str
    is_shortened: bool
    is_supported: bool
    is_matching_expected: bool = True
    error_message: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        res = {
            "originalUrl": self.original_url,
            "resolvedUrl": self.resolved_url,
            "platform": self.platform,
            "platformName": self.platform_name,
            "isShortened": self.is_shortened,
            "isSupported": self.is_supported,
            "isMatchingExpected": self.is_matching_expected,
        }
        if self.error_message:
            res["errorMessage"] = self.error_message
        return res
