// ─────────────────────────────────────────────────────────────────────────────
// Stream & Format DTOs
// ─────────────────────────────────────────────────────────────────────────────

export interface StreamFormatDto {
  formatId: string;
  quality: string;
  format: string;
  size: string;
  rawSize?: number;
  streamType: 'full' | 'mute' | 'audio' | 'stream' | 'muxed';
  hasAudio?: boolean;
  hasVideo?: boolean;
  fps?: string;
  bitrate?: string;
  url?: string;
  /** Codec video (ví dụ: av01, vp9, h264) */
  vcodec?: string;
  /** Codec audio (ví dụ: opus, aac, mp3) */
  acodec?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Subtitle & Chapter DTOs
// ─────────────────────────────────────────────────────────────────────────────

export interface SubtitleDto {
  lang: string;
  name: string;
  ext: string;
  url?: string;
  isAutoGenerated?: boolean;
}

export interface ChapterDto {
  title: string;
  startTime: number;
  endTime: number;
  startFormatted: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Image / Gallery DTOs
// ─────────────────────────────────────────────────────────────────────────────

export interface MediaImageDto {
  id: string | number;
  url: string;
  title: string;
  resolution?: string;
  size?: string;
  type?: 'image' | 'video' | 'gif';
  ext?: string;
  thumb?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main Media Metadata DTO
// ─────────────────────────────────────────────────────────────────────────────

export interface MediaMetadataDto {
  id: string;
  platform: string;
  title: string;
  author: string;
  authorUrl: string;
  duration: string;
  views: string;
  likes?: string;
  comments?: string;
  thumbnail: string;
  highResThumbnail?: string;
  type: 'video' | 'album' | 'audio' | 'playlist' | 'live';
  originalUrl: string;
  description?: string;
  tags?: string[];
  uploadDate?: string;
  subtitles?: SubtitleDto[];
  chapters?: ChapterDto[];
  streams?: StreamFormatDto[];
  images?: MediaImageDto[];
  playlistItems?: CrawlMediaItemDto[];

  /** True nếu đây là live stream đang phát */
  isLive?: boolean;

  /** URL HLS/DASH trực tiếp cho live stream */
  liveStreamUrl?: string;

  /** True nếu đây là video Reels (Instagram / Facebook) */
  isReel?: boolean;

  /** True nếu đây là video Shorts (YouTube) */
  isShort?: boolean;

  /** Tổng số item trong playlist/channel (nếu biết) */
  playlistCount?: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Profile / Crawl DTOs
// ─────────────────────────────────────────────────────────────────────────────

export interface CrawlMediaItemDto {
  id: string | number;
  type: 'video' | 'image' | 'audio';
  title: string;
  duration?: string;
  quality?: string;
  size?: string;
  thumb: string;
  url: string;
  author?: string;
  uploadDate?: string;
  views?: string;
  likes?: string;
  isLive?: boolean;
  isReel?: boolean;
  isShort?: boolean;
}

export interface ProfileCrawlResultDto {
  platform: string;
  name: string;
  handle: string;
  url: string;
  avatar: string;
  stats: string;
  media: CrawlMediaItemDto[];
  /** Tổng số media trên profile (nếu biết) */
  totalCount?: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Request DTOs (Input)
// ─────────────────────────────────────────────────────────────────────────────

export interface ExtractMediaRequest {
  url: string;
  /** Trình duyệt dùng để trích xuất cookies (tùy chọn) */
  browser?: string;
}

export interface CrawlProfileRequest {
  url: string;
  limit?: number;
  mediaType?: 'all' | 'video' | 'image';
  platform?: string;
  /** Trình duyệt dùng để trích xuất cookies (tùy chọn) */
  browser?: string;
  /** Bắt đầu từ vị trí item số mấy (playlist/channel) */
  rangeStart?: number;
  /** Kết thúc ở vị trí item số mấy */
  rangeEnd?: number;
}

export interface DownloadStreamRequest {
  url: string;
  formatId?: string;
  isAudio?: boolean;
  audioFormat?: string;
  audioBitrate?: string;
  startTime?: string;
  endTime?: string;
  format?: string;
  streamType?: string;
  isMute?: boolean;
  title?: string;
  /** Bật SponsorBlock: bỏ qua sponsor/intro/outro trên YouTube */
  sponsorBlock?: boolean;
  /** Nhúng thumbnail vào file audio sau khi tải */
  embedThumbnail?: boolean;
  /** Nhúng metadata vào file audio */
  embedMetadata?: boolean;
  /** Trình duyệt dùng để lấy cookies (tùy chọn) */
  browser?: string;
}

export interface BrowsersResponseDto {
  current: string;
  defaultConfigured: string;
  browsers: {
    id: string;
    name: string;
    detected: boolean;
    profilePath?: string;
  }[];
}

export interface DownloadZipItem {
  url: string;
  filename: string;
  referer?: string;
}

export interface DownloadZipRequest {
  items: DownloadZipItem[];
  zipName?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// System Config DTO (Response từ /api/media/config)
// ─────────────────────────────────────────────────────────────────────────────

export interface SystemConfigDto {
  browserCookies: string;
  cookiesFileSet: boolean;
  enableSponsorBlock: boolean;
  embedThumbnail: boolean;
  embedMetadata: boolean;
  maxPlaylistLimit: number;
  downloadTimeoutMs: number;
  pixivConfigured: boolean;
  deviantartConfigured: boolean;
}

// ─────────────────────────────────────────────────────────────────────────────
// Health Check DTO (Response từ /api/health)
// ─────────────────────────────────────────────────────────────────────────────

export interface HealthCheckDto {
  status: 'ok' | 'degraded' | 'error';
  ytDlp: {
    available: boolean;
    version?: string;
    path?: string;
  };
  galleryDl: {
    available: boolean;
    version?: string;
    path?: string;
  };
  ffmpeg: {
    available: boolean;
    version?: string;
  };
  atomicParsley: {
    available: boolean;
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Resolve URL DTOs (Giải mã link rút gọn và kiểm tra nền tảng)
// ─────────────────────────────────────────────────────────────────────────────

export interface ResolveUrlRequest {
  url: string;
  expectedPlatform?: string;
}

export interface ResolveUrlResponseDto {
  originalUrl: string;
  resolvedUrl: string;
  isShortened: boolean;
  platform: string | null;
  expectedPlatform?: string;
  matchesExpected?: boolean;
  error?: string;
}
